In [1]:
import numpy as np

In [2]:
def relaxation_method(x0,A,b,m):
    n=np.size(b)
    omega=1.1
    for k in range(m):
        print("\n\n")
        print("k=",k+1)
        for i in range(n):
            print("i=",i+1)
            print("\n")
            rk=b-A@x0
            print("A@x0=",A@x0)
            print("rk=",rk)
            x0[i]=x0[i]+omega*rk[i]/A[i,i]
            print("X=",x0)
            print("\n")
    return x0

In [3]:
A=np.array([[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]],dtype=np.float64)
b=np.array([6,6,6,6,6],dtype=np.float64)
x0=np.array([0,0,0,0,0],dtype=np.float64)
relaxation_method(x0,A,b,2)




k= 1
i= 1


A@x0= [0. 0. 0. 0. 0.]
rk= [6. 6. 6. 6. 6.]
X= [1.65 0.   0.   0.   0.  ]


i= 2


A@x0= [ 6.6  -1.65  3.3  -1.65  0.  ]
rk= [-0.6   7.65  2.7   7.65  6.  ]
X= [ 1.65  -2.805  0.     0.     0.   ]


i= 3


A@x0= [ 3.795  6.765  0.495  1.155 -5.61 ]
rk= [ 2.205 -0.765  5.505  4.845 11.61 ]
X= [ 1.65   -2.805   1.2111  0.      0.    ]


i= 4


A@x0= [ 5.0061  7.9761  6.5505 -0.0561 -6.8211]
rk= [ 0.9939 -1.9761 -0.5505  6.0561 12.8211]
X= [ 1.65      -2.805      1.2111     1.6654275  0.       ]


i= 5


A@x0= [ 5.0061     9.6415275  4.8850725  6.60561   -5.1556725]
rk= [ 0.9939    -3.6415275  1.1149275 -0.60561   11.1556725]
X= [ 1.65       -2.805       1.2111      1.6654275   3.06780994]





k= 2
i= 1


A@x0= [8.07390994 9.6415275  1.81726256 6.60561    7.11556725]
rk= [-2.07390994 -3.6415275   4.18273744 -0.60561    -1.11556725]
X= [ 1.07967477 -2.805       1.2111      1.6654275   3.06780994]


i= 2


A@x0= [ 5.79260901 10.21185273  0.6766121   7.17593523  7.11556725]
r

array([ 1.07967477, -1.260654  ,  2.04248922,  1.9953725 ,  2.0495358 ])

In [50]:
np.linalg.inv(A)@b

array([-0.79764706,  2.79529412, -0.25882353, -2.25176471])

In [4]:
def Gauss_Seidel(x0,A,b,m):
    n=np.size(b)
    for k in range(m):
        for i in range(n):
            s=0
            for j in range(n):
                if j!=i:
                    s=s-A[i,j]*x0[j]    
            x0[i]=1/A[i,i]*(s+b[i])
        print("k=",k+1)
        print("x0=",x0)
    return x0

In [21]:
def Jacobi(x0,A,b,m):
    m=m+1
    n=np.size(b)
    x_matrix=np.zeros((m,n))
    x_matrix[0,:]=x0
   # print(x0)
    for k in np.arange(1,m):
        for i in range(n):
            s=0.0
            for j in range(n):
                if j!=i:
                    s=s-A[i,j]*x_matrix[k-1,j]
            x_matrix[k,i]=1/A[i,i]*(s+b[i])
    print(x_matrix)
    return

In [31]:
A=np.array([[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]],dtype=np.float64)
b=np.array([6,6,6,6,6],dtype=np.float64)
x0=np.array([0,0,0,0,0],dtype=np.float64)
Gauss_Seidel(x0,A,b,2)

k= 1
x0= [ 1.5     -2.5      1.1      1.525    2.64375]
k= 2
x0= [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]


array([ 1.1890625 , -1.52135417,  1.86239583,  1.88252604,  2.25564453])

In [29]:
np.linalg.inv(A)@b

array([-0.79764706,  2.79529412, -0.25882353, -2.25176471])

In [45]:
A=np.array([[3,-1,1],[3,6,2],[3,3,7]],dtype=np.float64)
b=np.array([1,0,4],dtype=np.float64)
x0=np.array([0,0,0],dtype=np.float64)
Jacobi(x0,A,b,9)

[[ 0.          0.          0.        ]
 [ 0.33333333  0.          0.57142857]
 [ 0.14285714 -0.35714286  0.42857143]
 [ 0.07142857 -0.21428571  0.66326531]
 [ 0.04081633 -0.25680272  0.63265306]
 [ 0.03684807 -0.23129252  0.66399417]
 [ 0.03490444 -0.23975543  0.6547619 ]
 [ 0.03516089 -0.23570619  0.65922185]
 [ 0.03502399 -0.23732106  0.65737656]
 [ 0.03510079 -0.23663751  0.65812732]]


In [18]:
x0

array([ 0.11111111, -0.22222222,  0.61904762])

In [46]:
def Jacobi2(x0,A,b):
    n=np.size(b)
    x1=[]
    temp1=10
    temp0=max(x0)
    count=0
    while (abs(temp0-temp1)/abs(temp1)>0.001):
        print("Count=",count)
        for i in range(n):
            s=0
            for j in range(n):
                if i!=j:
                    s=s-A[i,j]*x0[j]
            x1.append((s+b[i])/A[i,i])
        #x1_mat=np.array(x1)
        temp0=max(x0)
        temp1=max(x1)
        print("x0=",x0)
        print("x1=",x1)
        print("Relative Error=",abs(temp0-temp1)/abs(temp1))
        x0=x1
        x1=[]
        count=count+1
    return

In [47]:
A=np.array([[3,-1,1],[3,6,2],[3,3,7]],dtype=np.float64)
b=np.array([1,0,4],dtype=np.float64)
x0=np.array([0,0,0],dtype=np.float64)
Jacobi2(x0,A,b)

Count= 0
x0= [0. 0. 0.]
x1= [0.3333333333333333, 0.0, 0.5714285714285714]
Relative Error= 1.0
Count= 1
x0= [0.3333333333333333, 0.0, 0.5714285714285714]
x1= [0.14285714285714288, -0.35714285714285715, 0.42857142857142855]
Relative Error= 0.3333333333333333
Count= 2
x0= [0.14285714285714288, -0.35714285714285715, 0.42857142857142855]
x1= [0.07142857142857144, -0.21428571428571427, 0.6632653061224489]
Relative Error= 0.35384615384615387
Count= 3
x0= [0.07142857142857144, -0.21428571428571427, 0.6632653061224489]
x1= [0.040816326530612256, -0.2568027210884354, 0.6326530612244898]
Relative Error= 0.04838709677419342
Count= 4
x0= [0.040816326530612256, -0.2568027210884354, 0.6326530612244898]
x1= [0.03684807256235826, -0.23129251700680276, 0.6639941690962099]
Relative Error= 0.04720087815587259
Count= 5
x0= [0.03684807256235826, -0.23129251700680276, 0.6639941690962099]
x1= [0.03490443796566245, -0.23975542597991575, 0.6547619047619049]
Relative Error= 0.014100185528756753
Count= 6
x0= [0.0

In [41]:
np.linalg.inv(A)@b

array([ 0.03508772, -0.23684211,  0.65789474])

In [62]:
def Gauss_Seidel2(x0,A,b):
    n=np.size(b)
    temp0=max(x0)
    temp1=10
    count=1
    x_prev=np.zeros_like(x0)
    while (abs(temp0-temp1)/abs(temp1)>0.001):
        print("Count=",count)
        for i in range(np.size(x0)):
            x_prev[i]=x0[i]
        #print(x_prev)
        for i in range(n):
            s=0
            for j in range(n):
                if j!=i:
                    s=s-A[i,j]*x0[j]    
            x0[i]=1/A[i,i]*(s+b[i])
        temp0=max(x_prev)
        temp1=max(x0)
        print("x0=",x_prev)
        print("x1=",x0)
        print("Relative Error=",abs(temp0-temp1)/abs(temp1))
        count=count+1
    return x0

In [63]:
A=np.array([[3,-1,1],[3,6,2],[3,3,7]],dtype=np.float64)
b=np.array([1,0,4],dtype=np.float64)
x0=np.array([0,0,0],dtype=np.float64)
Gauss_Seidel2(x0,A,b)

Count= 1
x0= [0. 0. 0.]
x1= [ 0.33333333 -0.16666667  0.5       ]
Relative Error= 1.0
Count= 2
x0= [ 0.33333333 -0.16666667  0.5       ]
x1= [ 0.11111111 -0.22222222  0.61904762]
Relative Error= 0.19230769230769218
Count= 3
x0= [ 0.11111111 -0.22222222  0.61904762]
x1= [ 0.05291005 -0.23280423  0.64852608]
Relative Error= 0.04545454545454557
Count= 4
x0= [ 0.05291005 -0.23280423  0.64852608]
x1= [ 0.03955656 -0.23595364  0.65559875]
Relative Error= 0.010788108375195537
Count= 5
x0= [ 0.03955656 -0.23595364  0.65559875]
x1= [ 0.0361492  -0.23660752  0.65733928]
Relative Error= 0.0026478410513141697
Count= 6
x0= [ 0.0361492  -0.23660752  0.65733928]
x1= [ 0.03535107 -0.23678863  0.65775895]
Relative Error= 0.0006380395137795539


array([ 0.03535107, -0.23678863,  0.65775895])

In [60]:
a=np.array([1,2,3])
b=a
print(b)
a[1]=5
print(b)

[1 2 3]
[1 5 3]


In [57]:
b

[1, 2, 3]

In [58]:
a=[2,2,4]

In [59]:
b

[1, 2, 3]